import { StyleSheet } from 'react-native';

export default colors =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    mainContent: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingBottom: 90,
    },
    welcomeContainer: {
      alignItems: 'center',
      width: '90%',
    },
    welcomeText: {
      color: colors.primary,
      fontSize: 16,
      fontWeight: '700',
      letterSpacing: 2,
      marginBottom: 8,
      textTransform: 'uppercase',
    },
    appName: {
      color: colors.primary,
      fontSize: 48,
      fontWeight: '900',
      marginBottom: 30,
      textTransform: 'uppercase',
      letterSpacing: 1,
      textShadowColor: `${colors.primary}33`,
      textShadowOffset: { width: 0, height: 2 },
      textShadowRadius: 8,
    },
    greetingContainer: {
      alignItems: 'center',
      marginBottom: 40,
    },
    greetingText: {
      color: colors.subtext,
      fontSize: 24,
      fontWeight: '300',
      marginBottom: -8,
    },
    userName: {
      color: colors.primary,
      fontSize: 32,
      fontWeight: '600',
      textTransform: 'capitalize',
    },
    logoutButton: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 20,
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 25,
      backgroundColor: `${colors.primary}22`,
      borderWidth: 1,
      borderColor: `${colors.primary}33`,
    },
    logoutText: {
      color: colors.primary,
      marginLeft: 8,
      fontSize: 16,
      fontWeight: '600',
    },
    bottomNavContainer: {
      position: 'absolute',
      bottom: 25,
      left: '10%',
      right: '10%',
      backgroundColor: colors.card,
      borderRadius: 30,
      paddingVertical: 15,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.25,
      shadowRadius: 20,
      elevation: 15,
      borderWidth: 1,
      borderColor: `${colors.primary}15`,
    },
    bottomNav: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'center',
    },
    navButton: {
      alignItems: 'center',
    },
    navIcon: {
      fontSize: 24,
      color: colors.subtext,
    },
    navIconActive: {
      fontSize: 24,
      color: colors.primary,
    },
    bubble: {
      width: 50,
      height: 50,
      borderRadius: 25,
      justifyContent: 'center',
      alignItems: 'center',
    },
    activeBubble: {
      backgroundColor: `${colors.primary}22`,
      transform: [{ scale: 1.1 }],
    },
    introContainer: {
      marginTop: 20,
      backgroundColor: colors.surface,
      borderRadius: 12,
      padding: 16,
      shadowColor: '#000',
      shadowOpacity: 0.1,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 3,
    },
    introTitle: {
      fontSize: 18,
      fontWeight: '600',
      marginBottom: 8,
      color: colors.primary,
    },
    introText: {
      fontSize: 14,
      color: colors.text,
      lineHeight: 20,
    },    
  });
