import { StyleSheet, Platform } from 'react-native';

export default function createStyles(colors) {
  return StyleSheet.create({
    safeArea: { 
      flex: 1, 
      backgroundColor: colors.background,
    },
    container: { 
      flex: 1, 
      backgroundColor: colors.background,
    },
    floatingBackButton: {
      position: 'absolute',
      top: Platform.OS === 'ios' ? 60 : 30,
      left: 20,
      backgroundColor: colors.card,
      borderRadius: 20,
      padding: 2,
      shadowColor: colors.overlay,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 3,
      elevation: 5,
      zIndex: 10,
    },
    loadingContainer: { 
      flex: 1, 
      justifyContent: 'center', 
      alignItems: 'center', 
      backgroundColor: colors.background,
    },
    messagesWrapper: { 
      flex: 1,
      zIndex: 1,
    },
    messagesContainer: {
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 16,
      backgroundColor: colors.background,
    },
    messageRow: { 
      flexDirection: 'row', 
      alignItems: 'flex-end', 
      marginBottom: 12,
    },
    botRow: { justifyContent: 'flex-start' },
    userRow: { justifyContent: 'flex-end' },
    botAvatar: { marginRight: 8 },
    userAvatar: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 10,
      padding: 5,
    },
    avatarImage: {
      width: 32,
      height: 32,
      borderRadius: 16,
      marginLeft: 10,
    },
    messageContainer: { maxWidth: '80%' },
    botContainer: { alignItems: 'flex-start' },
    userContainer: { alignItems: 'flex-end' },
    botBubble: {
      backgroundColor: colors.card,
      borderRadius: 15,
      padding: 12,
      borderWidth: 1.5,
      borderColor: colors.border,
    },
    userBubble: {
      backgroundColor: colors.card,
      borderRadius: 15,
      padding: 12,
      borderWidth: 1.5,
      borderColor: colors.border,
    },
    messageText: {
      fontSize: 16,
      fontFamily: 'Poppins_400Regular',
      lineHeight: 22,
      color: colors.text,
    },
    messageTime: {
      fontSize: 11,
      fontFamily: 'Poppins_400Regular',
      marginTop: 4,
      padding: 5,
      color: colors.subtext,
    },
    mapButton: { marginTop: 8 },
    mapButtonText: {
      fontSize: 16,
      fontFamily: 'Poppins_400Regular',
      color: colors.primary,
    },
    inputContainer: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      width: '100%',
      backgroundColor: colors.background,
      padding: 10,
      zIndex: 5,
    },
    inputCard: {
      borderRadius: 20,
      padding: 12,
      backgroundColor: colors.card,
      shadowColor: colors.overlay,
      shadowOffset: { width: 0, height: -3 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    inputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 6,
    },
    input: {
      flex: 1,
      fontFamily: 'Poppins_400Regular',
      fontSize: 16,
      color: colors.text,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.inputBackground,
    },
    placeInput: { marginRight: 8 },
    radiusContainer: { flexDirection: 'row', width: 110 },
    radiusInput: {
      flex: 1,
      marginRight: 8,
      textAlign: 'center',
      color: colors.text,
    },
    unitButton: {
      width: 46,
      height: 38,
      backgroundColor: colors.card,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
    },
    unitText: {
      fontFamily: 'Poppins_400Regular',
      fontSize: 16,
      color: colors.text,
    },
    descriptionInput: {
      marginRight: 8,
      minHeight: 44,
      textAlignVertical: 'top',
      color: colors.text,
    },
    sendButton: {
      width: 46,
      height: 46,
      backgroundColor: colors.primary,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    sendButtonDisabled: { opacity: 0.5 },

    // === NEW: a generic nested-card style ===
    subCard: {
      backgroundColor: colors.subcard,
      borderRadius: 12,
      padding: 12,
      marginBottom: 8,
    },

    // changed to use subcard
    placeCard: {
      borderRadius: 12,
      padding: 12,
      marginBottom: 8,
      backgroundColor: colors.subcard,
      borderColor: colors.border,
      borderWidth: 1.5,
      overflow: 'hidden',
    },
    placeName: {
      fontSize: 17,
      fontFamily: 'Poppins_600SemiBold',
      color: colors.text,
      marginBottom: 4,
    },
    placeAddress: {
      fontSize: 14,
      fontFamily: 'Poppins_400Regular',
      marginBottom: 4,
      color: colors.subtext,
    },
    placeRating: {
      fontSize: 14,
      fontFamily: 'Poppins_400Regular',
      marginBottom: 4,
      color: colors.text,
    },
    placeSummary: {
      fontSize: 15,
      fontFamily: 'Poppins_400Regular',
      paddingBottom: 10,
      color: colors.text,
    },
    placeExplanation: {
      fontSize: 14,
      fontFamily: 'Poppins_400Regular',
      color: colors.text,
    },
    placeOpeningHours: {
      fontSize: 14,
      fontFamily: 'Poppins_400Regular',
      color: colors.text,
    },
    placePrice: {
      fontSize: 14,
      fontFamily: 'Poppins_400Regular',
      color: colors.text,
    },
    suggestionsContainer: {
      maxHeight: 150,
      backgroundColor: colors.subcard,  // <— now uses subcard
      borderColor: colors.border,
      borderWidth: 1.5,
      borderRadius: 12,
      marginTop: 2,
      marginBottom: 8,
      overflow: 'hidden',
      paddingHorizontal: 12,
      elevation: 3,
      shadowColor: colors.overlay,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
    },
    suggestionItem: {
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    suggestionText: {
      fontSize: 16,
      fontFamily: 'Poppins_400Regular',
      color: colors.text,
    },
    placeInputWrapper: {
      flex: 1,
      position: 'relative',
    },
  });
}
